AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API for denniscm.com frontend

Conditions:
  CreateProdResources: !Equals
    - !Ref AWS::AccountId
    - 572540046516 # Dennis account ID (Production)

Globals:
  Function:
    Runtime: python3.7
    Handler: app.lambda_handler
    Architectures:
      - x86_64
    Timeout: 15
    MemorySize: 128
    Tracing: Active

Resources:
  StateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Tracing:
        Enabled: true
      DefinitionUri: statemachine/statemachine.asl.json
      DefinitionSubstitutions:
        ParseReposFunctionArn: !GetAtt ParseReposFunction.Arn
        UploadReposFunctionArn: !GetAtt UploadReposFunction.Arn
      Events:
        StateChange:
          Type: ScheduleV2
          Properties:
            Name: ParseGithubReposSchedule
            Description: Fetch Github repos for denniscm every day at 20:00
            ScheduleExpression: cron(0 20 ? * MON-FRI *)
            State: !If
              - CreateProdResources
              - ENABLED
              - DISABLED
            RetryPolicy:
              MaximumRetryAttempts: 3
    Connectors:
      StateMachineConnector:
        Properties:
          Destination:
            - Id: ParseReposFunction
            - Id: UploadReposFunction
          Permissions:
            - Write

  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET, POST, OPTIONS'"
        AllowHeaders: "'content-type, x-api-key'"
        AllowOrigin: "'*'"
      Models:
        Empty:
          type: object

  ParseReposFunction:
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: parse_repos/

  UploadReposFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: upload_repos/
    Connectors:
      DynamoConnector:
        Properties:
          Destination:
            Id: DynamoTable
          Permissions:
            - Write

  GetReposFunction:
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: get_repos/
        Events:
          GetReposEvent:
            Type: Api
            Properties:
              RestApiId: !Ref Api
              Path: /repos
              Method: get
      Connectors:
        DynamoConnector:
          Properties:
            Destination:
              Id: DynamoTable
            Permissions:
              - Read

  DynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: GithubPublicRepos
      BillingMode: PAY_PER_REQUEST
      DeletionProtectionEnabled: !If
        - CreateProdResources
        - True
        - False
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S

Outputs:
  ApiId:
    Description: The API Id of denniscm.com backend
    Value: !Ref Api
    Export:
      Name: DennisCmBackendApiId

  ApiUrl:
    Description: The API url of denniscm.com backend
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/Prod"
